name: Report a Bug With the "scanner" (v4) CLI Commands
description: Report an issue with one of the commands contained in the "@salesforce/sfdx-scanner" Salesforce CLI plugin.
title: "[BUG][scanner] <YOUR_TITLE_HERE>"
body:
  - type: checkboxes
    attributes:
      label: Have you tried to resolve this issue yourself first?
      description: |
        You can often resolve "scanner" issues on your own. Follow these steps:
        1. Read the error message.
        2. Read the [Salesforce Code Analyzer v4](https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/code-analyzer-3x.html) documentation.
        3. Double-check the command that you ran. Make sure that items like file names, method names, and category names are correctly spelled and cased.
        4. Verify that your code is syntactically valid.
        5. Verify that the error is reproducible on another computer.
        6. Check open and closed [issues](https://github.com/forcedotcom/code-analyzer/issues) to see if your issue is already logged.
      options:
        - label: I confirm I have gone through the above steps and still have an issue to report.
          required: true
  - type: textarea
    attributes:
      label: Bug Description
      description: Provide a clear and concise overview of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Output / Logs
      description: Attach any output or logs here.
      placeholder: |
        Add log output or drag files here.
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: List the steps that you used to reproduce the bug behavior. Be as specific and clear as possible.
      placeholder: |
        1. I first do ...
        2. Then I do ...
        3. Lastly, I do ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Provide a clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      description: |
        What is your computer's operating system?
      placeholder: |
        Example: macOS Sonoma 14.4.1
    validations:
      required: true
  - type: input
    attributes:
      label: Salesforce CLI Version
      description: |
        What do you get when you run the "sf --version" command?
      placeholder: |
        Example: @salesforce/cli/2.90.4 darwin-x64 node-v22.15.0
    validations:
      required: true
  - type: input
    attributes:
      label: Scanner Plugin Version
      description: |
        What do you get when you run the "sf plugins" command?
      placeholder: |
        Example: @salesforce/sfdx-scanner 4.12.0 (4.12.0)
    validations:
      required: true
  - type: input
    attributes:
      label: Node Version
      description: |
        What do you get when you run the "node --version" command?
      placeholder: |
        Example: v23.4.0
    validations:
      required: false
  - type: input
    attributes:
      label: Java Version
      description: |
        What do you get when you run the "java -version" command?
      placeholder: |
        Example: openjdk version "11.0.17.0.1" 2022-10-18 LTS
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context (Screenshots, Files, etc)
      description: Add any other context about the problem.
      placeholder: |
        Drag any files or screenshots you have here.
  - type: textarea
    attributes:
      label: Workaround
      description: What ways have you found to sidestep the problem? If you haven't found a workaround, what have you tried so far?
  - type: dropdown
    attributes:
      label: Urgency
      description: What is the severity of the problem?
      options:
        - Low
        - Moderate
        - High
        - Critical
      default: 0
    validations:
      required: true
