name: Report a Bug with scanner run dfa
description: Report an issue with the scanner run dfa command.
title: "[BUG] <YOUR_TITLE_HERE>"
labels: []
body:
- type: dropdown
  attributes:
    label: Have you tried to resolve this issue yourself first?
    description: |
      Oftentimes, you can resolve `scanner run dfa` issues on your own. Follow these steps:
      1. Read the error message.
      2. Read [Salesforce Graph Engine](https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/salesforce-graph-engine.html) documentation.
      3. Read our guide for [troubleshooting Graph Engine errors](https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/troubleshooting.html).
      4. Read our guidelines to resolve [LimitReached errors](https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/working-with-graph-engine.html#limitreached-errors) and [path evaluation timeouts](https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/troubleshooting.html#issues-using-salesforce-graph-engine).
      5. Read our [Guide to Writing Graph Engine-Friendly Code](https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/graph-engine-friendly-code.html).
      6. Double-check the command that you entered. Ensure that items like file names, method names, and category names are correctly spelled and cased.
      7. Verify that your code is syntactically valid.
      8. Verify that the error is reproducible on another machine.
      9. Check open and closed [issues](https://github.com/forcedotcom/sfdx-scanner/issues) to see if your issue is already logged.
      10. If there's no existing issue that covers your situation, log a new issue.

      If you're listing a managed package on AppExchange, prepare for the security review by following the instructions in the [Scan Your Solution with Salesforce Code Analyzer](https://developer.salesforce.com/docs/atlas.en-us.packagingGuide.meta/packagingGuide/security_review_code_analyzer_scan.htm) section of the ISVforce Guide.
      *Note: In your scan report, if you see an InternalExecutionError or a LimitReached error, you can still submit for AppExchange security review. These errors aren't blockers.*

      **I confirm that I have gone through these steps and still have an issue to report.**
      <sup>(You must select "Yes" to create an issue.)</sup>
    options:
    - ''
    - "Yes"
  validations:
    required: true
- type: textarea
  attributes:
    label: Bug Description
    description: Provide a clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Output / Logs
    description: Attach any output or logs here. The log for the Salesforce Graph Engine can be found in `~/.sfdx-scanner/sfge.log`. If the error message mentions a specific graph vertex, check its DefiningType and BeginLine properties and include the code at that line.
    placeholder: |
      Add log output here or drag files here.
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: List out the steps that you used to reproduce the bug behavior. Be as specific and clear as possible.
    placeholder: |
      1. I first do ...
      2. Then I do ...
      3. Lastly, I do ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: Provide a clear and concise description of what you expected to happen.
  validations:
    required: true
- type: input
  attributes:
    label: Operating System
    description: |
      What is your machine's operating system?
    placeholder: |
      Example: MacOS Sonoma 14.4.1
  validations:
    required: true
- type: input
  attributes:
    label: Salesforce CLI Version
    description: |
      What do you get from the command "sf --version"?
    placeholder: |
      Example: @salesforce/cli/2.40.7 darwin-arm64 node-v20.12.2
  validations:
    required: true
- type: input
  attributes:
    label: Code Analyzer Plugin (@salesforce/sfdx-scanner) Version
    description: |
      What do you get from the command "sf plugins"?
    placeholder: |
      Example: @salesforce/sfdx-scanner 4.1.0 (latest-beta)
  validations:
    required: true
- type: input
  attributes:
    label: Java Version
    description: |
      What do you get from the command "java -version"?
    placeholder: |
      Example: openjdk version "11.0.17.0.1" 2022-10-18 LTS
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Context (Screenshots, Files, etc)
    description: Add any other context about the problem.
    placeholder: |
      Drag any files or screenshots you have here.
- type: textarea
  attributes:
    label: Workaround
    description: What ways have you found to sidestep the problem? If you haven't found a workaround, what have you tried so far?
- type: dropdown
  attributes:
    label: Urgency
    description: What is the severity of the problem?
    options:
    - Low
    - Moderate
    - High
    - Critical
    default: 0
  validations:
    required: true
