name: Report a False Result with scanner run
description: Report false results in scanner run scan reports. If you're submitting your managed package for AppExchange security review, include documentation of your false results with your submission.
title: "[False Result] <YOUR_TITLE_HERE>"
labels: []
body:
- type: dropdown
  attributes:
    label: Have you verified this is Salesforce Code Analyzer specific?
    description: |
      Oftentimes, a rule is not directly owned by Salesforce Code Analyzer but instead owned by the underlying tool associated with the rule (like PMD or eslint for example). Before reporting this issue, please check to see if running the corresponding tool separate from Salesforce Code Analyzer also gives you a false positive. If so, then please create an issue with that corresponding tool instead of here. Otherwise, create your issue here.

      **I have verified that the issue is only reproducible when running through Salesforce Code Analyzer.**
      <sup>(You must select "Yes" to create an issue.)</sup>
    options:
    - ''
    - "Yes"
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: Provide a clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Output / Logs
    description: Attach any output or logs here
    placeholder: |
      Add log output here or drag files here.
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: List out the steps that you used to reproduce the bug behavior. Be as specific and clear as possible.
    placeholder: |
      1. I first do ...
      2. Then I do ...
      3. Lastly, I do ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: Provide a clear and concise description of why you believe this is a false result.
    placeholder: |
      I expected the result to be ...
      I believe the provide result is wrong because ...
  validations:
    required: true
- type: input
  attributes:
    label: Operating System
    description: |
      What is your machine's operating system?
    placeholder: |
      Example: MacOS Sonoma 14.4.1
  validations:
    required: true
- type: input
  attributes:
    label: Salesforce CLI Version
    description: |
      What do you get from the command "sf --version"?
    placeholder: |
      Example: @salesforce/cli/2.40.7 darwin-arm64 node-v20.12.2
  validations:
    required: true
- type: input
  attributes:
    label: Code Analyzer Plugin (@salesforce/sfdx-scanner) Version
    description: |
      What do you get from the command "sf plugins"?
    placeholder: |
      Example: @salesforce/sfdx-scanner 4.1.0 (latest-beta)
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Context (Screenshots, Files, etc)
    description: Add any other context about the problem.
    placeholder: |
      Drag any files or screenshots you have here.
- type: textarea
  attributes:
    label: Workaround
    description: What ways have you found to sidestep the problem? If you haven't found a workaround, what have you tried so far?
- type: dropdown
  attributes:
    label: Urgency
    description: What is the severity of the problem?
    options:
    - Low
    - Moderate
    - High
    - Critical
    default: 0
  validations:
    required: true
