name: setup-test-env
on:
  workflow_call: # As per documentation, the colon is necessary even though no config is required

jobs:
  setup-test-env:
    runs-on: ubuntu-latest
    steps:
      # First thing's first; we need to get the code.
      - uses: actions/checkout@v2
      - run: ls
      - run: pwd
      - run: git branch
