name: apply-npm-tag-to-version
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Select Package Name:'
        required: true
        type: choice
        options:
          - '@salesforce/plugin-code-analyzer'
          # TODO: Remove after April Release
          - '@salesforce/sfdx-scanner' 
      tag_name:
        description: 'Tag Name (ex: latest):'
        required: true
        type: string
      version:
        description: 'Version (ex: 5.2.0):'
        required: true
        type: string
      confirm:
        description: 'Check this box to confirm that you understand that applying a tag using this action is only recommended for emergency rollback situations and that you understand the consequences.'
        required: true
        type: boolean

jobs:
  publish_package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4