#TODO: remove v4 with April Release
name: daily-smoke-tests-v4
on:
  workflow_dispatch: # As per documentation, the colon is necessary even though no config is required.

jobs:
  smoke-test:
    uses: ./.github/workflows/run-tests.yml
    with:
      node-matrix: "[{version: 'lts/*', artifact: 'lts'}, {version: 'latest', artifact: 'latest'}]"
  v4-smoke-test:
    runs-on: macos-latest
    steps:
      - name: Invoke v4 smoke tests
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'daily-smoke-tests.yml',
              ref: 'dev-4'
            });
