name: experimentation
on:
  workflow_call:
    inputs:
      node-matrix:
        description: "An array of node versions against which the tests should be run"
        required: false
        type: string
        default: "['lts/*']"

jobs:
  do-thing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'v3-6-2'
      - run: echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        id: get-branch-commit
      - uses: actions/checkout@v3
        with:
          ref: 'v3.6.2'
      - run: echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        id: get-tag-commit
      - uses: actions/checkout@v3
        with:
          ref: 'release-3'
      - run: echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        id: get-release-commit
      - run: echo ${{steps.get-branch-commit.outputs.COMMIT_ID }} ${{ steps.get-tag-commit.outputs.COMMIT_ID }} ${{ steps.get-release-commit.outputs.COMMIT_ID }}
