name: experimentation
on:
  workflow_call:
    inputs:
      node-matrix:
        description: "An array of node versions against which the tests should be run"
        required: false
        type: string
        default: "['lts/*']"
      tag:
        description: "beep"
        required: false
        type: string
        default: "v3.2.2"

jobs:
  do-thing:
    strategy:
      matrix:
        v: [0, 0, 0, 1]
    runs-on: ubuntu-latest
    steps:
      - run: sleep 15 && exit ${{ matrix.v }}
  second-thing:
    runs-on: ubuntu-latest
    needs: do-thing
    steps:
      - run: echo beep
