name: experimentation
on:
  workflow_call:
    inputs:
      node-matrix:
        description: "An array of node versions against which the tests should be run"
        required: false
        type: string
        default: "['lts/*']"
  workflow_dispatch:
    inputs:
      tag:
        description: a tag
        type: string
        required: true
      dry-run:
        description: a boolean
        type: boolean
        required: false
        default: false

jobs:
  do-thing:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.tag }}
      - run: echo ${{ inputs.dry-run }}
