name: experimentation
on:
  workflow_call:
    inputs:
      node-matrix:
        description: "An array of node versions against which the tests should be run"
        required: false
        type: string
        default: "['lts/*']"

jobs:
  do-thing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: salesforcecli/github-workflows/.github/actions/getPreReleaseTag@main
        id: distag
      - run: echo ${{ steps.distag.outputs.tag }}
