name: experimentation
on:
  workflow_call:
    inputs:
      node-matrix:
        description: "An array of node versions against which the tests should be run"
        required: false
        type: string
        default: "['lts/*']"

jobs:
  do-thing:
    runs-on: ubuntu-latest
    steps:
      # We want to check out the release-3 branch.
      - uses: actions/checkout@v3
        with:
          ref: 'v3-6-2'
      # Get the commit at the head of this branch and output it for later use.
      - run: echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        id: get-release-commit
      # Checkout the tag we want to release.
      - uses: actions/checkout@v3
        with:
          ref: 'v3.6.2'
      # Get the commit associated with this tag and output it for later use.
      - run: echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        id: get-tag-commit
      # Compare the two commits to make sure they're the same.
      - name: Fail non-matching commits
        if: ${{ steps.get-release-commit.outputs.COMMIT_ID != steps.get-tag-commit.outputs.COMMIT_ID }}
        run: |
          echo "${{ steps.get-release-commit.outputs.COMMIT_ID }} differed from ${{ steps.get-tag-commit.outputs.COMMIT_ID }}"
          exit 1
