name: heartbeat-envvar-test
on:
  pull_request: # As per documentation, the colon is necessary even though no config is required.
jobs:
  heartbeat-envvar-test:
    strategy:
      # By default, if any job in a matrix fails, all other jobs are immediately cancelled. This makes the jobs run to completion instead.
      fail-fast: false
      matrix:
        os: [{vm: ubuntu-latest, exe: .sh}, {vm: windows-2019, exe: .cmd}]
        node: ['lts/*']
    runs-on: ${{ matrix.os.vm }}
    timeout-minutes: 60
    steps:
      # === Setup. We need to get the code, set up nodejs, and create the results directory. ===
      - uses: actions/checkout@v2
        with:
          ref: 'release'
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: mkdir smoke-test-results

      - name: Set environment variables
        id: envvar_setup
        shell: bash
        run: |
          if [[ -z "${{ secrets.CLI_VERSION }}" ]]; then
            echo "CLI_VERSION=latest" >> $GITHUB_ENV
          else
            echo "CLI_VERSION=${{ secrets.CLI_VERSION }}" >> $GITHUB_ENV
          fi
          if [[ -z "${{ secrets.SCANNER_VERSION }}" ]]; then
            echo "SCANNER_VERSION=latest" >> $GITHUB_ENV
          else
            echo "SCANNER_VERSION=${{ secrets.SCANNER_VERSION }}" >> $GITHUB_ENV
          fi
          if [[ -z "${{ secrets.FORCE_SMOKE_TEST_FAIL }}" ]]; then
            echo "FORCE_SMOKE_TEST_FAIL=false" >> $GITHUB_ENV
          else
            echo "FORCE_SMOKE_TEST_FAIL=${{ secrets.FORCE_SMOKE_TEST_FAIL }}" >> $GITHUB_ENV
          fi

      - name: Read environment variables
        id: envvar_read
        shell: bash
        run: |
          echo "Desired cli version: ${{ env.CLI_VERSION }}"
          echo "Desired scanner version: ${{ env.SCANNER_VERSION }}"
          echo "Should tests force fail: ${{ env.FORCE_SMOKE_TEST_FAIL }}"


      - name: Fire PagerDuty Alert
        id: fire_alert
        shell: bash
        env:
          RUN_LINK: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          generate_post_data() {
          # This is known as a HereDoc, and it lets us declare multi-line input ending when the specified limit string,
          # in this case EOF, is encoutered.
          cat <<EOF
          {"payload": {
            "summary": "Artifically induced failure. Do not panic",
            "source": "Github Actions",
            "severity": "critical",
            "custom_details": "Desired CLI: ${{ env.CLI_VERSION }}. Desired scanner: ${{ env.SCANNER_VERSION }}. Should tests fail: ${{ env.FORCE_SMOKE_TEST_FAIL }}."
          },
          "links": [{
            "href": "${{ env.RUN_LINK }}",
            "text": "Link to action execution"
          }],
          "event_action": "trigger",
          "dedup_key": "GH-HB-${{ matrix.os.vm }}-${{ matrix.node }}",
          "routing_key": "${{ secrets.PAGERDUTY_HEARTBEAT_KEY }}"
          }
          EOF
          }
          # Make our POST request
          curl --request POST --data "$(generate_post_data)" https://events.pagerduty.com/v2/enqueue
