name: pagerduty-test
on:
  pull_request: # As per documentation, the colon is necessary even though there's
jobs:
  pagerduty-test:
    strategy:
      # By default, if any job in a matrix fails, all other jobs are immediately cancelled. This makes the jobs run to completion instead.
      fail-fast: false
      matrix:
        os: [{vm: ubuntu-latest, exe: .sh}, {vm: windows-2019, exe: .cmd}]
        node: ['lts/*']
    runs-on: ${{ matrix.os.vm }}
    timeout-minutes: 60
    steps:
      # === Report any problems ===
      - name: Report problems
        shell: bash
        env:
          # A link to this run, so the PagerDuty assignee can quickly get here.
          RUN_LINK: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          # Define a helper function to create our POST request's data, to sidestep issues with nested quotations.
          generate_post_data() {
          # This is known as a HereDoc, and it lets us declare multi-line input ending when the specified limit string,
          # in this case EOF, is encoutered.
          cat <<EOF
          {"payload": {
            "summary": "test alert",
            "source": "Github Actions",
            "severity": "critical",
            "custom_details": "SFDX install: who cares. Scanner install: who cares. Smoke tests: who cares."
          },
          "links": [{
            "href": "${{ env.RUN_LINK }}",
            "text": "Link to action execution"
          }],
          "event_action": "trigger",
          "dedup_key": "GH-HB-${{ matrix.os.vm }}-${{ matrix.node }}",
          "routing_key": "${{ secrets.TEST_PAGERDUTY_KEY }}"
          }
          EOF
          }
          # Make our POST request
          curl --request POST --data "$(generate_post_data)" https://events.pagerduty.com/v2/enqueue
