name: production-smoke-tests
on:
  pull_request
#  schedule:
#    - cron: '45 1,5,9,13,17,21 * * *'
jobs:
  production-smoke-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
        node: ['lts/*']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm view sfd-cli
      - run: echo y | sfdx plugins:install @salesforce/sfdx-scanner
      - run: mkdir smoke-test-results
      # ==== Only one of the following two steps will be run =====
      - name: Windows smoke tests
        if: ${{ matrix.os == 'windows-2019' }}
        run: smoke-tests/smoke-test.cmd sfdx
      - name: POSIX smoke tests
        if: ${{ matrix.os != 'windows-2019' }}
        run: smoke-tests/smoke-test.sh sfdx
      # =====
      - name: Report failures
        if: ${{ failure() }}
        run: echo there was a failure
