name: production-smoke-tests
on:
  workflow_dispatch
#  schedule:
#    - cron: '45 1,5,9,13,17,21 * * *'
jobs:
  production-smoke-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
        node: [lts]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm install sfdx-cli
      - run: sfdx plugins:install @salesforce/sfdx-scanner
      - run: sfdx scanner:rule:list
