name: production-smoke-tests
on:
  pull_request
#  schedule:
#    - cron: '45 1,5,9,13,17,21 * * *'
jobs:
  production-smoke-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
        node: ['lts/*']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm view sfd-cli
      - run: echo y | sfdx plugins:install @salesforce/sfdx-scanner
      - run: mkdir smoke-test-results
      # ==== Only one of the following two steps will be run =====
      - name: Windows smoke tests
        if: ${{ matrix.os == 'windows-2019' }}
        run: smoke-tests/smoke-test.cmd sfdx
      - name: POSIX smoke tests
        if: ${{ matrix.os != 'windows-2019' }}
        run: smoke-tests/smoke-test.sh sfdx
      # =====
      - name: create url
        if: ${{ failure() }}
        run: |
          echo https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          echo ${{github.run_number}} ${{github.event_name}}
      - name: attempt retyr
        if: ${{ failure() && github.run_number < 23 }}
        run: curl --request POST --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/rerun
#      - name: Retry up to twice
#        if: ${{ failure() && github.run_number < 3 }}
#        shell: bash
#        run: |
#
#      - name: Report failures
#        if: ${{ failure() }}
#        shell: bash
#        run: |
#          curl --request POST \
#          --data '{"payload": {
#          "summary": "Production smoke-tests failed on ${{ matrix.os }}",
#          "source": "Github Actions","severity": "critical"
#          },
#          "event_action": "trigger",
#          "routing_key": "${{ secrets.TEST_PAGERDUTY_KEY }}"
#          }' \
#          https://events.pagerduty.com/v2/enqueue
#
