name: production-heartbeat
on:
  workflow_dispatch: # As per documentation, the colon is necessary even though no config is required.
  schedule:
    # Cron syntax is "minute[0-59] hour[0-23] date[1-31] month[1-12] day[0-6]". '*' is 'any value', and multiple values
    # can be specified with comma-separated lists. All times are UTC.
    # So this expression means "run at 45 minutes past 1, 5, and 9 AM/PM UTC". The hours were chosen so that
    # the jobs run only close to business hours of Central Time.
    # Days were chosen to run only from Monday through Friday.
    - cron: '45 13,17,21 * * 1,2,3,4,5'
jobs:
  production-heartbeat:
    runs-on: macos-latest
    steps:
      - name: Invoke v4 workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'heartbeat-v4.yml',
              ref: 'dev-4'
            });
