name: publish-to-npm
on:
  release:
    types: [released]
  # Support manual releases in case something goes wrong, or we need to do a test.
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to be published
        type: string
        required: true

jobs:
  # Step 1: Verify that the tag we're trying to release is a valid candidate for publishing.
  verify-candidate-tag:
    runs-on: ubuntu-latest
    steps:
      # Check out the main branch, and get its head commit as output for later.
      - uses: actions/checkout@v4
        with:
          ref: 'main'