name: run-tests
on:
  workflow_call:


jobs:
  # Step 1: Set up the environment and build the things we need.
  setup-test-env:
    runs-on: ubuntu-latest
    steps:
      # First thing's first; we need to get the code.
      - uses: actions/checkout@v2
      # Next, we need to make sure we're using v1.8 and Node LTS
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8' # v1.8 required for building SFGE
      # Next we install our dependencies and build, so we can run unit tests
      - run: yarn
      - run: yarn build
      # We also need to create a tarball for the smoke tests
      - run: npm pack
      # Finally, we upload the entire working directory as an artifact, so it can
      # be used in later jobs.
      - run: zip working-dir.zip ./* -r
      - uses: actions/upload-artifact@v3
        with:
          name: working-directory
          path: ./working-dir.zip

  # Step 2: We run our tests.
  # Step 2A: Linux unit tests
  linux-unit-tests:
    runs-on: ubuntu-latest
    needs: setup-test-env
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: working-directory
      - run: ls
      - run: echo Running Linux Tests
  # Step 2B: Windows unit tests
  windows-unit-tests:
    runs-on: windows-2019
    needs: setup-test-env
    steps:
      - run: echo Running windows tests
  # Step 2C: Linux smoke tests
  linux-smoke-tests:
    runs-on: ubuntu-latest
    needs: setup-test-env
    steps:
      - run: echo Running linux smoke
  # Step 2D: Windows smoke tests
  windows-smoke-tests:
    runs-on: windows-2019
    needs: setup-test-env
    steps:
      - run: echo Running windows smoke
  # Step 2E: Self-evaluation on Linux
  self-evaluation:
    runs-on: ubuntu-latest
    needs: setup-test-env
    steps:
      - run: echo Running Self-eval
