name: update-alpha-rc-to-alpha
on:
  workflow_call:

jobs:
  do-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm dist-tag add @salesforce/plugin-code-analyzer@5.0.0-alpha.1 latest-alpha
