name: validate-pr
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  # We want to prevent cross-contamination between the 4.x and 5.x pipelines. So we should prevent PRs
  # based on this flow to merge into `dev-4` or `main-4`.
  # TODO: Remove this after the April release, since we won't care after that to maintain v4
  verify_target_branch:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.base_ref == 'dev-4' || github.base_ref == 'main-4' }}
        run: |
          echo "Forbidden to merge this branch into dev-4 or release-4"
          exit 1
  # We need to verify that the Pull Request's title matches the desired format.
  verify_pr_title:
    runs-on: ubuntu-latest
    name: Verify that PR title contains well-formed GUS work item tag.
    steps:
      # Private actions must check out repo first.
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify PR title
        uses: ./github-actions/verify-pr-title
        id: verify_pr_title
  # Separately, we also need to run all of our tests.
  run_tests:
    uses: ./.github/workflows/run-tests.yml

  test_other_action:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      # PREREQUISITES - Only needed if runner doesn't already satisfy these requirements
      - name: Ensure node v20.9.0 or greater
        uses: actions/setup-node@v4
        with:
          node-version: '>=20.9.0'
      - name: Ensure java v11 or greater
        uses: actions/setup-java@v4
        with:
          java-version: '>=11'
          distribution: 'zulu'
      - name: Ensure python v3.10 or greater
        uses: actions/setup-python@v5
        with:
          python-version: '>=3.10'
      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Install Latest Salesforce Code Analyzer CLI Plugin
        run: sf plugins install code-analyzer@latest

      - name: call other action
        uses: jfeingold35/sfdx-code-review-action@jf/exp
        with:
          github_token: ${{ github.token }}
          engine: "pmd"
          category: "Best Practices"

  test_action:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      # PREREQUISITES - Only needed if runner doesn't already satisfy these requirements
      - name: Ensure node v20.9.0 or greater
        uses: actions/setup-node@v4
        with:
          node-version: '>=20.9.0'
      - name: Ensure java v11 or greater
        uses: actions/setup-java@v4
        with:
          java-version: '>=11'
          distribution: 'zulu'
      - name: Ensure python v3.10 or greater
        uses: actions/setup-python@v5
        with:
          python-version: '>=3.10'
      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Install Latest Salesforce Code Analyzer CLI Plugin
        run: sf plugins install code-analyzer@latest
      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@jf/experiment-2
        with:
          run-arguments: --workspace . --view detail --output-file sfca_results.html --output-file sfca_results.json -c alt-config.yml
          results-artifact-name: salesforce-code-analyzer-results
          # github-token: ${{ github.token }}

      - name: Check the outputs to determine whether to fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-sev2-violations > 0 ||
          steps.run-code-analyzer.outputs.num-violations > 10
        run: exit 1
