name: validate-pr
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  # We want to prevent cross-contamination between the 4.x and 5.x pipelines. So we should prevent PRs
  # based on this flow to merge into `dev-4` or `main-4`.
  # TODO: Remove this after the April release, since we won't care after that to maintain v4
  verify_target_branch:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.base_ref == 'dev-4' || github.base_ref == 'main-4' }}
        run: |
          echo "Forbidden to merge this branch into dev-4 or release-4"
          exit 1
  # We need to verify that the Pull Request's title matches the desired format.
  verify_pr_title:
    runs-on: ubuntu-latest
    name: Verify that PR title contains well-formed GUS work item tag.
    steps:
      # Private actions must check out repo first.
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify PR title
        uses: ./github-actions/verify-pr-title
        id: verify_pr_title
  # Separately, we also need to run all of our tests.
  run_tests:
    uses: ./.github/workflows/run-tests.yml
